name: CI

on: 
  pull_request:
    branches:
    - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set Node.js 10.13.0
      uses: actions/setup-node@master
      with:
        node-version: 10.13.0

    - name: Install dependencies
      run: yarn

    - name: Run test suite
      run: yarn test
