name: CD

on:
  push:
    branches:
    - master

jobs:
  publish:
    name: publish
    runs-on: macos-latest
    steps:
    - name: 'Validate branch'
      if: startsWith(github.event.commits[0].message, '[Release]')
      run: echo "Invalid branch"

    - uses: actions/checkout@v2
      if: success()

    - name: Set Node.js 10.13.0
      if: success()
      uses: actions/setup-node@master
      with:
        node-version: 10.13.0

    - name: Install dependencies
      if: success()
      run: yarn install

    - name: Publish
      if: success()
      run: yarn lerna:publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}
