name: CD

on: 
  push:
    branches:
    - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Set Node.js 10.x
      uses: actions/setup-node@master
      with:
        node-version: 10.x

    - name: Install dependencies & build
      run: |
        yarn
        yarn run build

    - name: Publish to npm registry
      run: yarn run publish
      if: success()
      
    - name: Publish to Github Pages
      run: yarn run deploy
      if: success()
